In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("data/verif_concordance.csv")

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2128 entries, 0 to 2127
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             2128 non-null   int64
 1   heure_de_debut                 2128 non-null   object
 2   heure_de_fin                   2128 non-null   object
 3   date                           2128 non-null   object
 4   lieu_de_la_verification        2128 non-null   object
 5   appartenance_du_conducteur     2128 non-null   object
 6   type_de_verification           2128 non-null   object
 7   region                         2128 non-null   object
 8   presence_licence_transport     1727 non-null   object
 9   numero_licence                 1592 non-null   object
 10  presentation_permis_conduire   1665 non-null   object
 11  verification_liste_nominative  1614 non-null   object
 12  anomalie                       2128 non-null   object
 13  anomalie_de_chargement         2128 non-null   object
 14  anomalie_de_vehicule           2128 non-null   object
 15  is_surete                      2128 non-null   bool
 16  anomalie_suivi_de_tournee      2128 non-null   object
 17  agences_antennes               2121 non-null   object
 18  tournee                        2128 non-null   object
 19  pda                            2128 non-null   object
 20  jour                           2128 non-null   object
 21  heure_arrondie                 2128 non-null   object
 22  anomalie_list                  2128 non-null   object
 23  anomalie_vehicule_list         2128 non-null   object
 24  anomalie_tournee_list          2128 non-null   object
dtypes: bool(1), int64(1), object(23)
memory usage: 401.2+ KB

In [21]:
df[df["agences_antennes"].isna() == True]

,id,heure_de_debut,heure_de_fin,date,lieu_de_la_verification,appartenance_du_conducteur,type_de_verification,region,presence_licence_transport,numero_licence,...,is_surete,anomalie_suivi_de_tournee,agences_antennes,tournee,pda,jour,heure_arrondie,anomalie_list,anomalie_vehicule_list,anomalie_tournee_list
848,849,2026-03-07 11:22:41,2026-03-07 11:23:16,2026-03-07 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD EST,"Oui, licence de transport intérieur",NaN,...,False,['Aucune anomalie'],NaN,267341,K,Samedi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
849,850,2026-03-07 11:23:17,2026-03-07 11:24:05,2026-03-07 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD EST,"Oui, licence de transport intérieur",NaN,...,False,['Aucune anomalie'],NaN,267341,S,Samedi,11:30:00,['Colis en cabine'],['Aucune anomalie'],['Aucune anomalie']
850,851,2026-03-07 11:24:06,2026-03-07 11:24:48,2026-03-07 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD EST,"Oui, licence de transport intérieur",NaN,...,False,['Aucune anomalie'],NaN,267341,E,Samedi,11:30:00,['Colis en cabine'],['Aucune anomalie'],['Aucune anomalie']
933,934,2026-03-11 11:42:29,2026-03-11 11:43:26,2026-03-11 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,"Oui, licence de transport intérieur",NaN,...,False,['Aucune anomalie'],NaN,267341,S,Mercredi,11:30:00,['Colis en cabine'],['Aucune anomalie'],['Aucune anomalie']
934,935,2026-03-11 11:43:27,2026-03-11 11:44:18,2026-03-11 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,"Oui, licence de transport intérieur",NaN,...,False,['Aucune anomalie'],NaN,267341,N,Mercredi,11:30:00,['Colis en cabine'],['Aucune anomalie'],['Aucune anomalie']
1751,1752,2026-01-12 10:47:25,2026-01-12 10:55:16,2026-01-12 00:00:00,Agence / Antenne,DSP,Avant chargement,REGION SUD,NaN,NaN,...,True,['Aucune anomalie'],NaN,19,B,Lundi,11:00:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']
1882,1883,2026-02-13 11:16:12,2026-02-13 11:17:16,2026-02-13 00:00:00,Agence / Antenne,DSP,Après chargement,REGION SUD EST,NaN,NaN,...,True,['Aucune anomalie'],NaN,088314,B,Vendredi,11:30:00,['Aucune anomalie'],['Aucune anomalie'],['Aucune anomalie']

In [14]:
#df1 = pd.read_excel("data/VERIFICATION DE CONCORDANCE DE CHARGEMENT VERIFICATION DOCUMENTAIRE - ETAT DES VEHICULES.xlsx", engine="openpyxl")
df2 = pd.read_excel("data/SURETE - VERIFICATION DE CONCORDANCE DE CHARGEMENT 2026.xlsx", engine="openpyxl", skiprows=[1, 1])

In [16]:
df2.tail(30)

,ID,Heure de début,Heure de fin,Adresse de messagerie,Nom,Heure de la dernière modification,Date,Nom de la personne en charge de la vérification,Lieu de la vérification,Appartenance du conducteur,...,AGENCES/ANTENNES REGION IDF\n,ANOMALIE,ANOMALIE DE CHARGEMENT,Commentaires ( N° de colis...),ANOMALIE DE VEHICULE,Commentaires,Chauffeur sorti des effectifs ?,Sanction RH ?,ANOMALIE SUIVI DE TOURNEE,Actions prises et commentaires divers
368,370,2026-03-26 10:54:50,2026-03-26 10:56:18,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;Autre;,PAS DE LICENCE DANS VL. PATRON VENUE SUR PLACE...,NaN,NaN,NON,NON,NaN,NaN
369,371,2026-03-26 10:56:31,2026-03-26 10:58:00,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
370,372,2026-03-26 10:58:08,2026-03-26 10:59:29,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
371,373,2026-03-26 11:00:03,2026-03-26 11:02:01,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
372,374,2026-03-26 11:02:03,2026-03-26 11:03:55,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
373,375,2026-03-26 11:04:04,2026-03-26 11:05:26,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
374,376,2026-03-26 11:05:44,2026-03-26 11:07:45,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
375,377,2026-03-26 11:07:58,2026-03-26 11:08:59,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
376,378,2026-03-26 11:23:35,2026-03-26 11:26:54,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-26,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,Clef laissé sur le contact;,"CHAUFFEUR REVENU SUR AGENCE, VL STATIONNE GARE...",NON,NON,NaN,RAPPEL PROCESS AU CHAUFFEUR
377,379,2026-03-26 11:26:56,2026-03-26 11:31:26,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-25,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Autre;,PLUSIEURS COLIS DONT 2 SEPHORA NE SEMBLANT PAS...,Etat général;,NaN,NON,NON,NaN,NaN
378,380,2026-03-26 17:38:42,2026-03-26 17:41:12,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,381,2026-03-26 17:41:14,2026-03-26 17:42:42,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,382,2026-03-26 17:42:46,2026-03-26 17:43:49,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,383,2026-03-26 17:43:51,2026-03-26 17:45:05,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382,384,2026-03-26 17:45:07,2026-03-26 17:46:20,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383,385,2026-03-26 17:46:21,2026-03-26 17:48:00,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Oui,NaN,NaN,NaN,NaN,NaN,NaN,Colis en cabine;,NaN
384,386,2026-03-26 17:48:06,2026-03-26 17:49:22,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Oui,NaN,NaN,NaN,NaN,NaN,NaN,Moteur tournant ou clef sur le contact;Colis e...,NaN
385,387,2026-03-26 17:49:26,2026-03-26 17:50:35,Jonathan.Canu@cevalogistics.com,Jonathan CANU,NaN,2026-03-26,Jonathan CANU,Délocalisé,DSP,...,NaN,Oui,NaN,NaN,NaN,NaN,NaN,NaN,Moteur tournant ou clef sur le contact;Colis e...,NaN
386,388,2026-03-27 10:14:16,2026-03-27 10:16:18,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-27,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
387,389,2026-03-27 17:09:10,2026-03-27 17:13:39,Jean.Christophe.REPIQUET@cevalogistics.com,JEAN CHRISTOPHE REPIQUET,NaN,2026-03-27,Jean-Christophe REPIQUET,Agence / Antenne,DSP,...,NaN,Oui,NaN,NaN,NaN,NaN,NON,NON,Colis en cabine;,2 colis statutés en BAL OK. 1 colis RCS dépos...
388,390,2026-03-30 08:13:16,2026-03-30 08:35:47,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-06,Line VINAY,Agence / Antenne,COLIS PRIVE,...,CE15,Oui,NaN,NaN,NaN,NaN,NON,NON,Moteur tournant ou clef sur le contact;,NaN
389,391,2026-03-30 08:36:54,2026-03-30 08:45:23,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,DSP,...,CE15,Oui,Colis non scanné (prévu pour ce chauffeur-livr...,51004567320695470,NaN,NaN,NON,NON,NaN,NaN
390,392,2026-03-30 08:47:05,2026-03-30 08:51:15,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,DSP,...,CE15,Oui,Colis en cabine;Autre;Colis non scanné (prévu ...,Etiquette de colis Amazon pris en photo pour l...,Véhicule vitré;,NaN,NON,OUI,NaN,NaN
391,393,2026-03-30 08:51:49,2026-03-30 08:53:01,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,DSP,...,CE15,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
392,394,2026-03-30 08:53:02,2026-03-30 08:55:21,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,COLIS PRIVE,...,CE15,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
393,395,2026-03-30 08:55:45,2026-03-30 08:57:15,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,DSP,...,CE15,Oui,Colis en cabine;,NaN,NaN,NaN,NON,NON,NaN,NaN
394,396,2026-03-30 08:57:45,2026-03-30 08:59:10,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,DSP,...,CE15,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,397,2026-03-30 08:59:18,2026-03-30 09:01:02,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,DSP,...,CE15,Oui,Colis en cabine;,NaN,Véhicule vitré;,NaN,NON,NON,NaN,NaN
396,398,2026-03-30 09:01:14,2026-03-30 09:02:02,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-18,Line VINAY,Agence / Antenne,COLIS PRIVE,...,CE15,Non,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,399,2026-03-30 09:02:29,2026-03-30 09:04:55,line.vinay@cevalogistics.com,LINE VINAY,NaN,2026-03-17,Line VINAY,Agence / Antenne,COLIS PRIVE,...,CE15,Oui,NaN,NaN,NaN,NaN,NON,NON,Moteur tournant ou clef sur le contact;,NaN

In [17]:
set(df2.columns)

{'AGENCES/ ANTENNES REGION SUD EST',
 'AGENCES/ANTENNES REGION IDF\n',
 'AGENCES/ANTENNES REGION NORD EST',
 'AGENCES/ANTENNES REGION NORD OUEST',
 'AGENCES/ANTENNES REGION SUD OUEST',
 'ANOMALIE',
 'ANOMALIE DE CHARGEMENT\xa0',
 'ANOMALIE DE VEHICULE',
 'ANOMALIE SUIVI DE TOURNEE',
 'Actions prises et commentaires divers\xa0',
 'Adresse de messagerie',
 'Appartenance du conducteur',
 'Chauffeur sorti des effectifs ?',
 'Commentaires',
 'Commentaires ( N° de colis...)',
 'Date',
 'Heure de début',
 'Heure de fin',
 'Heure de la dernière modification',
 'ID',
 'Immatriculation',
 'LETTRE DE PDA',
 'Lieu de la vérification',
 'NUMERO DE TOURNEE',
 'Nom',
 'Nom de la personne en charge de la vérification',
 'REGION',
 'Sanction RH ?\xa0',
 'Type de vérification'}

In [9]:
set(df2.columns)

{'AGENCES/ ANTENNES REGION EST',
 'AGENCES/ANTENNES REGION NORD',
 'AGENCES/ANTENNES REGION OUEST',
 'AGENCES/ANTENNES REGION SUD',
 'ANOMALIE',
 'ANOMALIE DE CHARGEMENT\xa0',
 'ANOMALIE DE VEHICULE',
 'ANOMALIE SUIVI DE TOURNEE',
 'Adresse de messagerie',
 'Appartenance du conducteur',
 'Commentaires',
 'Commentaires ( N° de colis...)',
 'Commentaires divers\xa0',
 'Date',
 'Heure de début',
 'Heure de fin',
 'Heure de la dernière modification',
 'ID',
 'Lieu de la vérification',
 'Matière dangereuse',
 'Nom',
 'Nom de la personne en charge de la vérification',
 'REGION',
 'Tournée / PDA / Nom de la société si DSP',
 'Type de véhicule / immatriculation',
 'Type de vérification'}

In [161]:
def uniform_anomalies(df) :
    # Remplacer NaN
    df["anomalie_de_chargement"] = df["anomalie_de_chargement"].fillna("Aucune anomalie")
    
    # Split et nettoyage
    df["anomalie_list"] = df["anomalie_de_chargement"].apply(
        lambda x: [item.strip().rstrip(";") for item in x.split(";") if item.strip()]
    )
    
    # Mapping pour uniformiser
    mapping = {
        "Autre": "Autre",
        "Colis en cabine": "Colis en cabine",
        "Colis non scanné (prévu pour ce chauffeur-livreur)": "Colis non scanné",
        "Colis non prévu pour ce chauffeur-livreur": "Colis non prévu",
        "Colis non prévu pour ce chauffeur-livreur (prévenir sans délai le service sûreté)": "Colis non prévu",
        "Adhésif Colis Privé dans le véhicule": "Adhésif Colis Privé"
    }
    
    df["anomalie_de_chargement"] = df["anomalie_list"].apply(
        lambda lst: [mapping.get(item, item) for item in lst]
    )
    
    # Remplacer NaN
    df["anomalie_de_vehicule"] = df["anomalie_de_vehicule"].fillna("Aucune anomalie")
    
    # Split et nettoyage
    df["anomalie_vehicule_list"] = df["anomalie_de_vehicule"].apply(
        lambda x: [item.strip().rstrip(";") for item in x.split(";") if item.strip()]
    )

    # Mapping pour uniformiser
    mapping_vehicule = {
        "Clef laissé sur le contact": "Clef laissée sur le contact",
        "Clef laissée sur le contact": "Clef laissée sur le contact",
        "Défaut de verrouillage": "Défaut de verrouillage",
        "Etat général": "Etat général",
        "Manque séparation cabine/caisse": "Manque séparation cabine/caisse",
        "Passager non autorisé": "Passager non autorisé",
        "Véhicule vitré": "Véhicule vitré"
    }
    
    df["anomalie_de_vehicule"] = df["anomalie_vehicule_list"].apply(
        lambda lst: [mapping_vehicule.get(item, item) for item in lst]
    )
    
    # Remplacer NaN
    df["anomalie_suivi_de_tournee"] = df["anomalie_suivi_de_tournee"].fillna("Aucune anomalie")
    
    # Split et nettoyage
    df["anomalie_tournee_list"] = df["anomalie_suivi_de_tournee"].apply(
        lambda x: [item.strip().rstrip(";") for item in x.split(";") if item.strip()]
    )
    
    # Mapping pour uniformiser
    mapping_tournee = {
        "Colis en cabine": "Colis en cabine",
        "Colis non autorisé": "Colis non autorisé",
        "Défaut de verrouillage": "Défaut de verrouillage",
        "Moteur tournant ou clef sur le contact": "Moteur tournant ou clef sur le contact"
    }
    
    df["anomalie_suivi_de_tournee"] = df["anomalie_tournee_list"].apply(
        lambda lst: [mapping_tournee.get(item, item) for item in lst]
    )

    return df

In [162]:
df = uniform_anomalies(df)

In [163]:
df["anomalie_de_chargement"].value_counts()

anomalie_de_chargement
[Aucune anomalie]                                       3283
[Colis en cabine]                                        555
[Colis non scanné]                                        89
[Colis en cabine, Colis non scanné]                       47
[Autre]                                                   33
[Colis en cabine, Autre]                                  11
[Colis non prévu]                                          7
[Colis non scanné, Colis en cabine]                        6
[Colis non scanné, Autre]                                  4
[Adhésif Colis Privé]                                      3
[Colis en cabine, Adhésif Colis Privé]                     2
[Colis en cabine, Colis non scanné, Colis non prévu]       2
[Colis en cabine, Colis non scanné, Autre]                 1
[Colis en cabine, Colis non prévu]                         1
Name: count, dtype: int64

In [164]:
df["anomalie_de_vehicule"].value_counts()

anomalie_de_vehicule
[Aucune anomalie]                                                  3954
[Etat général]                                                       48
[Clef laissée sur le contact]                                        12
[Véhicule vitré]                                                      6
[Défaut de verrouillage]                                              5
[Manque séparation cabine/caisse]                                     4
[Manque séparation cabine/caisse, Véhicule vitré]                     3
[Passager non autorisé]                                               2
[Véhicule vitré, Manque séparation cabine/caisse]                     2
[Manque séparation cabine/caisse, Véhicule vitré, Etat général]       2
[Manque séparation cabine/caisse, Etat général]                       2
[Défaut de verrouillage, Véhicule vitré]                              1
[Défaut de verrouillage, Etat général]                                1
[Etat général, Manque séparation cabine/caisse]                       1
[Véhicule vitré, Etat général]                                        1
Name: count, dtype: int64

In [165]:
df["anomalie_suivi_de_tournee"].value_counts()

anomalie_suivi_de_tournee
[Aucune anomalie]                                                                    4029
[Colis en cabine]                                                                       8
[Défaut de verrouillage, Moteur tournant ou clef sur le contact, Colis en cabine]       4
[Défaut de verrouillage, Colis en cabine]                                               1
[Colis en cabine, Moteur tournant ou clef sur le contact, Défaut de verrouillage]       1
[Colis non autorisé]                                                                    1
Name: count, dtype: int64

In [177]:
anom_charg = df['anomalie_de_chargement'].explode()
anom_charg = anom_charg.explode()
print(anom_charg.head())
anom_charg = anom_charg[anom_charg.notna() & (anom_charg != "Aucune anomalie")]
print(anom_charg.head())
anom_charg = anom_charg.value_counts().head(10)
print(anom_charg)

0     ['Aucune anomalie']
1     ['Aucune anomalie']
2     ['Aucune anomalie']
3     ['Aucune anomalie']
4    ['Colis non scanné']
Name: anomalie_de_chargement, dtype: object
0     ['Aucune anomalie']
1     ['Aucune anomalie']
2     ['Aucune anomalie']
3     ['Aucune anomalie']
4    ['Colis non scanné']
Name: anomalie_de_chargement, dtype: object
anomalie_de_chargement
['Aucune anomalie']                        3283
['Colis en cabine']                         555
['Colis non scanné']                         89
['Colis en cabine', 'Colis non scanné']      47
['Autre']                                    33
['Colis en cabine', 'Autre']                 11
['Colis non prévu']                           7
['Colis non scanné', 'Colis en cabine']       6
['Colis non scanné', 'Autre']                 4
['Adhésif Colis Privé']                       3
Name: count, dtype: int64

In [174]:
anom_suivi

anomalie_suivi_de_tournee
Colis en cabine                           14
Défaut de verrouillage                     6
Moteur tournant ou clef sur le contact     5
Colis non autorisé                         1
Name: count, dtype: int64

In [168]:
set(anom_suivi)

{1, 5, 6, 14}

In [169]:
df.to_csv("verif_concordance.csv", index=False)