### Objectifs

- Nb controle par site 
- jour / heures de controle / par site
- nb_anomalie 
- classement site +/- anomalie
- % d'anomalie vs nb de controle effectué 
- nb_ de controle av apres chargement
- chauffeur CP ou DSP
- Anomalie CP / Délocalisé

In [53]:
# Controle contradictoire :  MCP Win => Distribution => Suivie Colis Reçu =>

In [54]:
import pandas as pd

In [57]:
df = pd.read_csv("verif_concordance1.csv")

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 19 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Id                                        568 non-null    int64
 1   Heure de début                            568 non-null    object
 2   Heure de fin                              568 non-null    object
 3   Date                                      568 non-null    object
 4   Lieu de la vérification                   568 non-null    object
 5   Appartenance du conducteur                568 non-null    object
 6   Tournée / PDA / Nom de la société si DSP  568 non-null    object
 7   Type de vérification                      568 non-null    object
 8   REGION                                    568 non-null    object
 9   ANOMALIE                                  568 non-null    object
 10  ANOMALIE DE CHARGEMENT                    373 non-null    object
 11  ANOMALIE DE VEHICULE                      40 non-null     object
 12  ANOMALIE SUIVI DE TOURNEE                 12 non-null     object
 13  AGENCES/ANTENNES                          568 non-null    object
 14  Tournée                                   558 non-null    float64
 15  PDA                                       553 non-null    object
 16  Nom de la société                         315 non-null    object
 17  jour                                      568 non-null    object
 18  heure_arrondie                            568 non-null    object
dtypes: float64(1), int64(1), object(17)
memory usage: 84.4+ KB

In [74]:
set(df["AGENCES/ANTENNES"])

{'AT0301',
 'AT2601',
 'AT4201',
 'AT4202',
 'AT6001',
 'AT6002',
 'AT6101',
 'AT7401',
 'AT7801',
 'CE01',
 'CE02',
 'CE03',
 'CE05',
 'CE07\xa0',
 'CE08',
 'CE09\xa0',
 'CE10',
 'CE12',
 'CE13',
 'CE14',
 'CE15',
 'CE16',
 'CE17',
 'CE18',
 'CE19',
 'CE20',
 'CE21',
 'CE26',
 'CE27',
 'CE28'}

### Nombre de contrôle par site

In [47]:
df_agence = df.copy()

In [48]:
df_agence["AGENCES/ANTENNES"].value_counts()

AGENCES/ANTENNES
CE18      101
CE28       80
CE07       47
AT7801     42
CE17       40
CE26       36
CE14       36
CE15       31
CE16       18
AT2601     16
CE03       13
CE27       13
AT4202     13
AT7401     12
CE09       10
AT4201     10
CE05        8
AT0301      6
CE01        6
CE12        6
AT6101      4
CE21        4
CE10        3
AT6002      2
CE02        2
AT6001      2
CE13        2
CE20        2
CE19        2
CE08        1
Name: count, dtype: int64

### jour / heures de controle / par site

In [49]:
df_agence.head(2)

,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,AGENCES/ANTENNES,Tournée,PDA,Nom de la société,jour,heure_arrondie
0,1,2025-03-13 07:47:40,2025-03-13 07:50:12,2025-03-12,Agence / Antenne,DSP,096320/C/JLH TRANSPORT EXPRESS,Après chargement,REGION EST,Oui,Colis en cabine,NaN,NaN,CE09,96320.0,C,JLH TRANSPORT EXPRESS,Jeudi,08:00:00
1,2,2025-03-13 07:50:36,2025-03-13 07:53:42,2025-03-12,Agence / Antenne,DSP,096363/F/TRANSPORT GNAGBO,Après chargement,REGION EST,Oui,Colis non scanné (prévu pour ce chauffeur-livr...,NaN,NaN,CE09,96363.0,F,TRANSPORT GNAGBO,Jeudi,08:00:00

In [65]:
df_agence.groupby(["AGENCES/ANTENNES","jour"]).count().reset_index()

,AGENCES/ANTENNES,jour,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,Tournée,PDA,Nom de la société,heure_arrondie
0,AT0301,Jeudi,2,2,2,2,2,2,2,2,2,2,0,0,0,2,2,2,2
1,AT0301,Vendredi,4,4,4,4,4,4,4,4,4,4,1,0,0,4,4,4,4
2,AT2601,Jeudi,5,5,5,5,5,5,5,5,5,5,1,0,0,5,5,5,5
3,AT2601,Lundi,6,6,6,6,6,6,6,6,6,6,3,0,0,6,6,6,6
4,AT2601,Mardi,4,4,4,4,4,4,4,4,4,4,3,0,0,3,3,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,CE28,Jeudi,16,16,16,16,16,16,16,16,16,16,13,0,0,16,16,15,16
80,CE28,Lundi,19,19,19,19,19,19,19,19,19,19,14,0,0,18,18,19,19
81,CE28,Mardi,8,8,8,8,8,8,8,8,8,8,7,0,0,8,8,8,8
82,CE28,Mercredi,27,27,27,27,27,27,27,27,27,27,20,2,2,27,26,16,27
83,CE28,Vendredi,10,10,10,10,10,10,10,10,10,10,6,0,0,9,9,10,10

In [66]:
df_agence.groupby(["AGENCES/ANTENNES","heure_arrondie"]).count().reset_index()

,AGENCES/ANTENNES,heure_arrondie,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,Tournée,PDA,Nom de la société,jour
0,AT0301,08:30:00,2,2,2,2,2,2,2,2,2,2,0,0,0,2,2,2,2
1,AT0301,11:00:00,4,4,4,4,4,4,4,4,4,4,1,0,0,4,4,4,4
2,AT2601,11:30:00,3,3,3,3,3,3,3,3,3,3,2,0,0,2,2,3,3
3,AT2601,12:00:00,6,6,6,6,6,6,6,6,6,6,2,0,0,6,6,6,6
4,AT2601,13:30:00,6,6,6,6,6,6,6,6,6,6,3,0,0,6,6,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,CE28,13:30:00,3,3,3,3,3,3,3,3,3,3,1,0,0,3,3,3,3
146,CE28,14:00:00,2,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2,2
147,CE28,14:30:00,6,6,6,6,6,6,6,6,6,6,5,0,0,6,6,6,6
148,CE28,15:30:00,2,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2,2
149,CE28,17:00:00,2,2,2,2,2,2,2,2,2,2,0,0,2,2,2,0,2

### Nombre d'anomalie / sites

In [68]:
df_agence.groupby(["AGENCES/ANTENNES","ANOMALIE"]).count().reset_index()

,AGENCES/ANTENNES,ANOMALIE,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,Tournée,PDA,Nom de la société,jour,heure_arrondie
0,AT0301,Non,5,5,5,5,5,5,5,5,5,0,0,0,5,5,5,5,5
1,AT0301,Oui,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1
2,AT2601,Non,8,8,8,8,8,8,8,8,8,0,0,0,8,8,8,8,8
3,AT2601,Oui,8,8,8,8,8,8,8,8,8,8,0,0,7,7,8,8,8
4,AT4201,Non,3,3,3,3,3,3,3,3,3,0,0,0,3,3,3,3,3
5,AT4201,Oui,7,7,7,7,7,7,7,7,7,6,0,0,7,7,6,7,7
6,AT4202,Non,6,6,6,6,6,6,6,6,6,0,0,0,6,6,6,6,6
7,AT4202,Oui,7,7,7,7,7,7,7,7,7,7,0,0,7,7,7,7,7
8,AT6001,Oui,2,2,2,2,2,2,2,2,2,2,0,0,2,2,0,2,2
9,AT6002,Non,1,1,1,1,1,1,1,1,1,0,0,0,1,1,0,1,1
10,AT6002,Oui,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,1
11,AT6101,Non,1,1,1,1,1,1,1,1,1,0,0,0,1,1,0,1,1
12,AT6101,Oui,3,3,3,3,3,3,3,3,3,3,0,0,3,3,0,3,3
13,AT7401,Non,8,8,8,8,8,8,8,8,8,0,0,0,8,8,8,8,8
14,AT7401,Oui,4,4,4,4,4,4,4,4,4,4,0,0,4,4,4,4,4
15,AT7801,Non,6,6,6,6,6,6,6,6,6,0,0,0,6,6,0,6,6
16,AT7801,Oui,36,36,36,36,36,36,36,36,36,31,10,0,36,36,8,36,36
17,CE01,Oui,6,6,6,6,6,6,6,6,6,6,1,0,6,6,0,6,6
18,CE02,Oui,2,2,2,2,2,2,2,2,2,2,0,0,2,2,1,2,2
19,CE03,Non,8,8,8,8,8,8,8,8,8,0,0,0,7,7,1,8,8
20,CE03,Oui,5,5,5,5,5,5,5,5,5,5,1,0,5,5,0,5,5
21,CE05,Non,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1
22,CE05,Oui,7,7,7,7,7,7,7,7,7,7,0,0,7,7,7,7,7
23,CE07,Non,11,11,11,11,11,11,11,11,11,0,0,0,10,10,11,11,11
24,CE07,Oui,36,36,36,36,36,36,36,36,36,33,0,2,35,35,33,36,36
25,CE08,Oui,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1
26,CE09,Non,3,3,3,3,3,3,3,3,3,0,0,0,3,3,3,3,3
27,CE09,Oui,7,7,7,7,7,7,7,7,7,7,0,0,7,7,7,7,7
28,CE10,Non,2,2,2,2,2,2,2,2,2,0,0,0,2,2,0,2,2
29,CE10,Oui,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,1
30,CE12,Non,3,3,3,3,3,3,3,3,3,0,0,0,3,3,0,3,3
31,CE12,Oui,3,3,3,3,3,3,3,3,3,3,1,0,3,3,1,3,3
32,CE13,Non,1,1,1,1,1,1,1,1,1,0,0,0,1,1,0,1,1
33,CE13,Oui,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1
34,CE14,Non,3,3,3,3,3,3,3,3,3,0,0,0,3,3,3,3,3
35,CE14,Oui,33,33,33,33,33,33,33,33,33,33,1,0,33,33,32,33,33
36,CE15,Non,11,11,11,11,11,11,11,11,11,0,0,0,11,10,2,11,11
37,CE15,Oui,20,20,20,20,20,20,20,20,20,18,3,2,20,19,3,20,20
38,CE16,Non,7,7,7,7,7,7,7,7,7,0,0,0,7,7,0,7,7
39,CE16,Oui,11,11,11,11,11,11,11,11,11,7,6,1,11,11,2,11,11
40,CE17,Non,11,11,11,11,11,11,11,11,11,0,0,0,11,11,4,11,11
41,CE17,Oui,29,29,29,29,29,29,29,29,29,25,2,4,29,28,7,29,29
42,CE18,Non,40,40,40,40,40,40,40,40,40,0,0,0,40,40,5,40,40
43,CE18,Oui,61,61,61,61,61,61,61,61,61,54,11,1,61,61,19,61,61
44,CE19,Oui,2,2,2,2,2,2,2,2,2,2,0,0,2,2,0,2,2
45,CE20,Oui,2,2,2,2,2,2,2,2,2,2,0,0,2,2,0,2,2
46,CE21,Non,3,3,3,3,3,3,3,3,3,0,0,0,3,3,3,3,3
47,CE21,Oui,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1
48,CE26,Non,5,5,5,5,5,5,5,5,5,0,0,0,2,2,5,5,5
49,CE26,Oui,31,31,31,31,31,31,31,31,31,31,0,0,30,30,30,31,31
50,CE27,Non,2,2,2,2,2,2,2,2,2,0,0,0,2,2,0,2,2
51,CE27,Oui,11,11,11,11,11,11,11,11,11,11,2,0,11,10,0,11,11
52,CE28,Non,17,17,17,17,17,17,17,17,17,0,0,0,16,16,16,17,17
53,CE28,Oui,63,63,63,63,63,63,63,63,63,60,2,2,62,61,52,63,63

In [72]:
dfg = (
    df_agence
    .groupby(['AGENCES/ANTENNES', 'ANOMALIE'], dropna=False)
    .size()
    .reset_index(name='nb_controles')
)

# Total par agence
dfg['total_agence'] = dfg.groupby('AGENCES/ANTENNES')['nb_controles'].transform('sum')

# % de chaque modalité Oui / Non
dfg['pct'] = (100 * dfg['nb_controles'] / dfg['total_agence']).round(2)

# Si tu veux une colonne 'taux_anomalie' renseignée seulement sur la ligne 'Oui'
dfg['taux_anomalie'] = np.where(
    dfg['ANOMALIE'].eq('Oui'),
    dfg['pct'],
    np.nan
)

dfg

,AGENCES/ANTENNES,ANOMALIE,nb_controles,total_agence,pct,taux_anomalie
0,AT0301,Non,5,6,83.33,NaN
1,AT0301,Oui,1,6,16.67,16.67
2,AT2601,Non,8,16,50.00,NaN
3,AT2601,Oui,8,16,50.00,50.00
4,AT4201,Non,3,10,30.00,NaN
5,AT4201,Oui,7,10,70.00,70.00
6,AT4202,Non,6,13,46.15,NaN
7,AT4202,Oui,7,13,53.85,53.85
8,AT6001,Oui,2,2,100.00,100.00
9,AT6002,Non,1,2,50.00,NaN
10,AT6002,Oui,1,2,50.00,50.00
11,AT6101,Non,1,4,25.00,NaN
12,AT6101,Oui,3,4,75.00,75.00
13,AT7401,Non,8,12,66.67,NaN
14,AT7401,Oui,4,12,33.33,33.33
15,AT7801,Non,6,42,14.29,NaN
16,AT7801,Oui,36,42,85.71,85.71
17,CE01,Oui,6,6,100.00,100.00
18,CE02,Oui,2,2,100.00,100.00
19,CE03,Non,8,13,61.54,NaN
20,CE03,Oui,5,13,38.46,38.46
21,CE05,Non,1,8,12.50,NaN
22,CE05,Oui,7,8,87.50,87.50
23,CE07,Non,11,47,23.40,NaN
24,CE07,Oui,36,47,76.60,76.60
25,CE08,Oui,1,1,100.00,100.00
26,CE09,Non,3,10,30.00,NaN
27,CE09,Oui,7,10,70.00,70.00
28,CE10,Non,2,3,66.67,NaN
29,CE10,Oui,1,3,33.33,33.33
30,CE12,Non,3,6,50.00,NaN
31,CE12,Oui,3,6,50.00,50.00
32,CE13,Non,1,2,50.00,NaN
33,CE13,Oui,1,2,50.00,50.00
34,CE14,Non,3,36,8.33,NaN
35,CE14,Oui,33,36,91.67,91.67
36,CE15,Non,11,31,35.48,NaN
37,CE15,Oui,20,31,64.52,64.52
38,CE16,Non,7,18,38.89,NaN
39,CE16,Oui,11,18,61.11,61.11
40,CE17,Non,11,40,27.50,NaN
41,CE17,Oui,29,40,72.50,72.50
42,CE18,Non,40,101,39.60,NaN
43,CE18,Oui,61,101,60.40,60.40
44,CE19,Oui,2,2,100.00,100.00
45,CE20,Oui,2,2,100.00,100.00
46,CE21,Non,3,4,75.00,NaN
47,CE21,Oui,1,4,25.00,25.00
48,CE26,Non,5,36,13.89,NaN
49,CE26,Oui,31,36,86.11,86.11
50,CE27,Non,2,13,15.38,NaN
51,CE27,Oui,11,13,84.62,84.62
52,CE28,Non,17,80,21.25,NaN
53,CE28,Oui,63,80,78.75,78.75

### nb_ de controle av apres chargement

In [88]:
df_agence.groupby(["ANOMALIE","Type de vérification"]).count().reset_index()

,ANOMALIE,Type de vérification,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,REGION,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,AGENCES/ANTENNES,Tournée,PDA,Nom de la société,jour,heure_arrondie
0,Non,Après chargement,104,104,104,104,104,104,104,104,0,0,0,104,101,101,64,104,104
1,Non,Avant chargement,56,56,56,56,56,56,56,56,0,0,0,56,56,55,14,56,56
2,Non,Suivi de tournée,6,6,6,6,6,6,6,6,0,0,0,6,3,3,6,6,6
3,Oui,Après chargement,355,355,355,355,355,355,355,355,337,35,0,355,352,350,215,355,355
4,Oui,Avant chargement,31,31,31,31,31,31,31,31,29,5,0,31,30,29,12,31,31
5,Oui,Suivi de tournée,16,16,16,16,16,16,16,16,7,0,12,16,16,15,4,16,16

### chauffeur CP ou DSP

In [94]:
df_agence.groupby(["ANOMALIE","Appartenance du conducteur"]).count().reset_index()

,ANOMALIE,Appartenance du conducteur,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,AGENCES/ANTENNES,Tournée,PDA,Nom de la société,jour,heure_arrondie
0,Non,COLIS PRIVE,10,10,10,10,10,10,10,10,0,0,0,10,10,10,8,10,10
1,Non,COLIS PRIVE LIVRAISON,26,26,26,26,26,26,26,26,0,0,0,26,25,25,24,26,26
2,Non,DSP,130,130,130,130,130,130,130,130,0,0,0,130,125,124,52,130,130
3,Oui,COLIS PRIVE,16,16,16,16,16,16,16,16,14,1,2,16,14,12,9,16,16
4,Oui,COLIS PRIVE LIVRAISON,17,17,17,17,17,17,17,17,15,0,0,17,16,16,11,17,17
5,Oui,DSP,369,369,369,369,369,369,369,369,344,39,10,369,368,366,211,369,369

### Type d'anomalie

In [105]:
df.head(2)[["Id","ANOMALIE DE CHARGEMENT","ANOMALIE DE VEHICULE", "ANOMALIE SUIVI DE TOURNEE"]]

,Id,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE
0,1,Colis en cabine,NaN,NaN
1,2,Colis non scanné (prévu pour ce chauffeur-livr...,NaN,NaN

In [106]:
cols = [
    'ANOMALIE DE CHARGEMENT',
    'ANOMALIE DE VEHICULE',
    'ANOMALIE SUIVI DE TOURNEE'
]

# (optionnel) traiter les chaînes vides comme NaN
df_agence[cols] = df_agence[cols].replace(r'^\s*$', pd.NA, regex=True)

# nombre d'anomalies par catégorie = nb de valeurs non nulles
compte_par_categorie = (
    df_agence[cols].notna().sum()
    .rename('nb_anomalies')
    .to_frame()
    .reset_index()
    .rename(columns={'index': 'categorie'})
)

print(compte_par_categorie)

                   categorie  nb_anomalies
0     ANOMALIE DE CHARGEMENT           373
1       ANOMALIE DE VEHICULE            40
2  ANOMALIE SUIVI DE TOURNEE            12

In [101]:
# chargement
df_agence.groupby(["ANOMALIE","ANOMALIE DE CHARGEMENT"]).count().reset_index().sort_values(by="Id", ascending=False)

,ANOMALIE,ANOMALIE DE CHARGEMENT,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,AGENCES/ANTENNES,Tournée,PDA,Nom de la société,jour,heure_arrondie
2,Oui,Colis en cabine,277,277,277,277,277,277,277,277,277,19,2,277,275,272,165,277,277
10,Oui,Colis non scanné (prévu pour ce chauffeur-livr...,33,33,33,33,33,33,33,33,33,1,0,33,32,32,14,33,33
6,Oui,Colis en cabine;Colis non scanné (prévu pour c...,30,30,30,30,30,30,30,30,30,1,1,30,29,29,23,30,30
1,Oui,Autre,11,11,11,11,11,11,11,11,11,1,0,11,11,11,7,11,11
4,Oui,Colis en cabine;Autre,6,6,6,6,6,6,6,6,6,0,0,6,6,6,4,6,6
12,Oui,Colis non scanné (prévu pour ce chauffeur-livr...,4,4,4,4,4,4,4,4,4,1,0,4,4,4,4,4,4
0,Oui,Adhésif Colis Privé dans le véhicule,3,3,3,3,3,3,3,3,3,0,0,3,3,3,2,3,3
11,Oui,Colis non scanné (prévu pour ce chauffeur-livr...,3,3,3,3,3,3,3,3,3,0,0,3,3,3,3,3,3
8,Oui,Colis en cabine;Colis non scanné (prévu pour c...,2,2,2,2,2,2,2,2,2,0,0,2,2,2,2,2,2
3,Oui,Colis en cabine;Adhésif Colis Privé dans le vé...,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1
5,Oui,Colis en cabine;Colis non prévu pour ce chauff...,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1
7,Oui,Colis en cabine;Colis non scanné (prévu pour c...,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1
9,Oui,Colis non prévu pour ce chauffeur-livreur,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1

In [103]:
# VEHICULE
df_agence.groupby(["ANOMALIE","ANOMALIE DE VEHICULE"]).count().reset_index().sort_values(by="Id", ascending=False)

,ANOMALIE,ANOMALIE DE VEHICULE,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE DE CHARGEMENT,ANOMALIE SUIVI DE TOURNEE,AGENCES/ANTENNES,Tournée,PDA,Nom de la société,jour,heure_arrondie
2,Oui,Etat général,20,20,20,20,20,20,20,20,20,13,0,20,20,20,3,20,20
0,Oui,Défaut de verrouillage,4,4,4,4,4,4,4,4,4,2,0,4,4,4,1,4,4
4,Oui,Manque séparation cabine/caisse,4,4,4,4,4,4,4,4,4,4,0,4,4,4,1,4,4
6,Oui,Manque séparation cabine/caisse;Véhicule vitré,3,3,3,3,3,3,3,3,3,1,0,3,3,3,0,3,3
5,Oui,Manque séparation cabine/caisse;Etat général,2,2,2,2,2,2,2,2,2,1,0,2,2,2,0,2,2
7,Oui,Manque séparation cabine/caisse;Véhicule vitré...,2,2,2,2,2,2,2,2,2,1,0,2,2,2,0,2,2
1,Oui,Défaut de verrouillage;Etat général,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1
3,Oui,Etat général;Manque séparation cabine/caisse,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1
8,Oui,Passager non autorisé,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1
9,Oui,Véhicule vitré;Etat général,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1
10,Oui,Véhicule vitré;Manque séparation cabine/caisse,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1

In [104]:
# VEHICULE
df_agence.groupby(["ANOMALIE","ANOMALIE SUIVI DE TOURNEE"]).count().reset_index().sort_values(by="Id", ascending=False)

,ANOMALIE,ANOMALIE SUIVI DE TOURNEE,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,AGENCES/ANTENNES,Tournée,PDA,Nom de la société,jour,heure_arrondie
0,Oui,Colis en cabine,7,7,7,7,7,7,7,7,7,3,0,7,7,6,1,7,7
3,Oui,Défaut de verrouillage;Moteur tournant ou clef...,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,3,3
1,Oui,Colis en cabine;Moteur tournant ou clef sur le...,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1
2,Oui,Défaut de verrouillage;Colis en cabine,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,1,1

### Tournée

In [97]:
df_agence.groupby(["AGENCES/ANTENNES","ANOMALIE","Tournée"]).count().reset_index().sort_values(by="Id",ascending=False).head(20)

,AGENCES/ANTENNES,ANOMALIE,Tournée,Id,Heure de début,Heure de fin,Date,Lieu de la vérification,Appartenance du conducteur,Tournée / PDA / Nom de la société si DSP,Type de vérification,REGION,ANOMALIE DE CHARGEMENT,ANOMALIE DE VEHICULE,ANOMALIE SUIVI DE TOURNEE,PDA,Nom de la société,jour,heure_arrondie
142,CE14,Oui,149911.0,12,12,12,12,12,12,12,12,12,12,1,0,12,12,12,12
301,CE28,Oui,287133.0,11,11,11,11,11,11,11,11,11,11,0,0,11,10,11,11
265,CE26,Oui,267338.0,10,10,10,10,10,10,10,10,10,10,0,0,10,10,10,10
266,CE26,Oui,267339.0,8,8,8,8,8,8,8,8,8,8,0,0,8,8,8,8
291,CE28,Oui,280101.0,8,8,8,8,8,8,8,8,8,8,0,0,8,6,8,8
264,CE26,Oui,267337.0,8,8,8,8,8,8,8,8,8,8,0,0,8,7,8,8
196,CE17,Oui,179426.0,8,8,8,8,8,8,8,8,8,7,1,1,8,2,8,8
233,CE18,Oui,187535.0,7,7,7,7,7,7,7,7,7,7,0,0,7,3,7,7
298,CE28,Oui,286939.0,6,6,6,6,6,6,6,6,6,6,0,0,6,6,6,6
102,CE07,Oui,73825.0,6,6,6,6,6,6,6,6,6,6,0,0,6,6,6,6
69,AT7801,Oui,187886.0,5,5,5,5,5,5,5,5,5,4,1,0,5,0,5,5
184,CE17,Non,179426.0,5,5,5,5,5,5,5,5,5,0,0,0,5,1,5,5
108,CE07,Oui,76969.0,5,5,5,5,5,5,5,5,5,5,0,0,5,4,5,5
104,CE07,Oui,76902.0,5,5,5,5,5,5,5,5,5,5,0,0,5,5,5,5
56,AT7801,Oui,187803.0,5,5,5,5,5,5,5,5,5,5,2,0,5,1,5,5
292,CE28,Oui,280136.0,5,5,5,5,5,5,5,5,5,5,0,0,5,4,5,5
230,CE18,Oui,187525.0,5,5,5,5,5,5,5,5,5,5,0,0,5,3,5,5
217,CE18,Non,189218.0,4,4,4,4,4,4,4,4,4,0,0,0,4,0,4,4
206,CE18,Non,187518.0,4,4,4,4,4,4,4,4,4,0,0,0,4,0,4,4
227,CE18,Oui,187517.0,4,4,4,4,4,4,4,4,4,4,0,0,4,1,4,4